// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_prior_rcpp
List get_prior_rcpp(std::string model, std::string prior, double r0, Nullable<NumericVector> p0, Nullable<NumericVector> y, Nullable<NumericVector> m, Nullable<NumericMatrix> Y, Nullable<NumericMatrix> K);
RcppExport SEXP _BKP_get_prior_rcpp(SEXP modelSEXP, SEXP priorSEXP, SEXP r0SEXP, SEXP p0SEXP, SEXP ySEXP, SEXP mSEXP, SEXP YSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::string >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< double >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type y(ySEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type m(mSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(get_prior_rcpp(model, prior, r0, p0, y, m, Y, K));
    return rcpp_result_gen;
END_RCPP
}
// kernel_matrix_rcpp
arma::mat kernel_matrix_rcpp(SEXP X, SEXP Xprime, NumericVector theta, std::string kernel, bool isotropic);
RcppExport SEXP _BKP_kernel_matrix_rcpp(SEXP XSEXP, SEXP XprimeSEXP, SEXP thetaSEXP, SEXP kernelSEXP, SEXP isotropicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Xprime(XprimeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< bool >::type isotropic(isotropicSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_matrix_rcpp(X, Xprime, theta, kernel, isotropic));
    return rcpp_result_gen;
END_RCPP
}
// loss_fun_rcpp
double loss_fun_rcpp(std::string model, std::string loss, SEXP K, Nullable<NumericVector> y, Nullable<NumericVector> m, Nullable<NumericMatrix> Y, Nullable<NumericVector> alpha0, Nullable<NumericVector> beta0, Nullable<NumericMatrix> alpha0_mat, Nullable<NumericVector> data_scale);
RcppExport SEXP _BKP_loss_fun_rcpp(SEXP modelSEXP, SEXP lossSEXP, SEXP KSEXP, SEXP ySEXP, SEXP mSEXP, SEXP YSEXP, SEXP alpha0SEXP, SEXP beta0SEXP, SEXP alpha0_matSEXP, SEXP data_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::string >::type loss(lossSEXP);
    Rcpp::traits::input_parameter< SEXP >::type K(KSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type y(ySEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type m(mSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type alpha0_mat(alpha0_matSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type data_scale(data_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(loss_fun_rcpp(model, loss, K, y, m, Y, alpha0, beta0, alpha0_mat, data_scale));
    return rcpp_result_gen;
END_RCPP
}
// optimize_bkp_theta_rcpp
Rcpp::List optimize_bkp_theta_rcpp(const arma::mat& Xnorm, const arma::vec& y, const arma::vec& m, const std::string& prior, const double r0, const double p0, const std::string& loss, const std::string& kernel, const bool isotropic, const arma::mat& init_gamma, const arma::vec& lower, const arma::vec& upper, const int max_iter, const int n_threads, const std::string& ess, Nullable<NumericVector> m_shepard_loo);
RcppExport SEXP _BKP_optimize_bkp_theta_rcpp(SEXP XnormSEXP, SEXP ySEXP, SEXP mSEXP, SEXP priorSEXP, SEXP r0SEXP, SEXP p0SEXP, SEXP lossSEXP, SEXP kernelSEXP, SEXP isotropicSEXP, SEXP init_gammaSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP max_iterSEXP, SEXP n_threadsSEXP, SEXP essSEXP, SEXP m_shepard_looSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xnorm(XnormSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const double >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< const double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type loss(lossSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type isotropic(isotropicSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_gamma(init_gammaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type ess(essSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type m_shepard_loo(m_shepard_looSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_bkp_theta_rcpp(Xnorm, y, m, prior, r0, p0, loss, kernel, isotropic, init_gamma, lower, upper, max_iter, n_threads, ess, m_shepard_loo));
    return rcpp_result_gen;
END_RCPP
}
// optimize_dkp_theta_rcpp
Rcpp::List optimize_dkp_theta_rcpp(const arma::mat& Xnorm, const arma::mat& Y, const std::string& prior, const double r0, const arma::vec& p0, const std::string& loss, const std::string& kernel, const bool isotropic, const arma::mat& init_gamma, const arma::vec& lower, const arma::vec& upper, const int max_iter, const int n_threads, const std::string& ess, Nullable<NumericVector> m_shepard_loo);
RcppExport SEXP _BKP_optimize_dkp_theta_rcpp(SEXP XnormSEXP, SEXP YSEXP, SEXP priorSEXP, SEXP r0SEXP, SEXP p0SEXP, SEXP lossSEXP, SEXP kernelSEXP, SEXP isotropicSEXP, SEXP init_gammaSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP max_iterSEXP, SEXP n_threadsSEXP, SEXP essSEXP, SEXP m_shepard_looSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xnorm(XnormSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const double >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type loss(lossSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type isotropic(isotropicSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type init_gamma(init_gammaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type ess(essSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type m_shepard_loo(m_shepard_looSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_dkp_theta_rcpp(Xnorm, Y, prior, r0, p0, loss, kernel, isotropic, init_gamma, lower, upper, max_iter, n_threads, ess, m_shepard_loo));
    return rcpp_result_gen;
END_RCPP
}
// qbetabinom_rcpp
IntegerVector qbetabinom_rcpp(NumericVector prob, NumericVector size, NumericVector alpha, NumericVector beta);
RcppExport SEXP _BKP_qbetabinom_rcpp(SEXP probSEXP, SEXP sizeSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(qbetabinom_rcpp(prob, size, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// shepard_m_rcpp
arma::vec shepard_m_rcpp(const arma::mat& Xquery_norm, const arma::mat& Xtrain_norm, const arma::vec& m, const double power);
RcppExport SEXP _BKP_shepard_m_rcpp(SEXP Xquery_normSEXP, SEXP Xtrain_normSEXP, SEXP mSEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xquery_norm(Xquery_normSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xtrain_norm(Xtrain_normSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const double >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(shepard_m_rcpp(Xquery_norm, Xtrain_norm, m, power));
    return rcpp_result_gen;
END_RCPP
}
// shepard_m_loo_rcpp
arma::vec shepard_m_loo_rcpp(const arma::mat& Xnorm, const arma::vec& m, const double power);
RcppExport SEXP _BKP_shepard_m_loo_rcpp(SEXP XnormSEXP, SEXP mSEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xnorm(XnormSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const double >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(shepard_m_loo_rcpp(Xnorm, m, power));
    return rcpp_result_gen;
END_RCPP
}
// twin_bkp_posterior_rcpp
Rcpp::List twin_bkp_posterior_rcpp(Rcpp::NumericMatrix Xquery_norm, Rcpp::NumericMatrix Xtrain_norm, Rcpp::NumericVector y, Rcpp::NumericVector m, Rcpp::IntegerVector g_indices, Rcpp::IntegerMatrix local_indices, Rcpp::NumericVector theta_g, double theta_l, std::string global_kernel, std::string local_kernel, bool isotropic, std::string prior, double r0, double p0, bool store_kernel);
RcppExport SEXP _BKP_twin_bkp_posterior_rcpp(SEXP Xquery_normSEXP, SEXP Xtrain_normSEXP, SEXP ySEXP, SEXP mSEXP, SEXP g_indicesSEXP, SEXP local_indicesSEXP, SEXP theta_gSEXP, SEXP theta_lSEXP, SEXP global_kernelSEXP, SEXP local_kernelSEXP, SEXP isotropicSEXP, SEXP priorSEXP, SEXP r0SEXP, SEXP p0SEXP, SEXP store_kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xquery_norm(Xquery_normSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xtrain_norm(Xtrain_normSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type g_indices(g_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type local_indices(local_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta_g(theta_gSEXP);
    Rcpp::traits::input_parameter< double >::type theta_l(theta_lSEXP);
    Rcpp::traits::input_parameter< std::string >::type global_kernel(global_kernelSEXP);
    Rcpp::traits::input_parameter< std::string >::type local_kernel(local_kernelSEXP);
    Rcpp::traits::input_parameter< bool >::type isotropic(isotropicSEXP);
    Rcpp::traits::input_parameter< std::string >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< double >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< bool >::type store_kernel(store_kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(twin_bkp_posterior_rcpp(Xquery_norm, Xtrain_norm, y, m, g_indices, local_indices, theta_g, theta_l, global_kernel, local_kernel, isotropic, prior, r0, p0, store_kernel));
    return rcpp_result_gen;
END_RCPP
}
// twin_dkp_posterior_rcpp
Rcpp::List twin_dkp_posterior_rcpp(Rcpp::NumericMatrix Xquery_norm, Rcpp::NumericMatrix Xtrain_norm, Rcpp::NumericMatrix Y, Rcpp::IntegerVector g_indices, Rcpp::IntegerMatrix local_indices, Rcpp::NumericVector theta_g, double theta_l, std::string global_kernel, std::string local_kernel, bool isotropic, std::string prior, double r0, Rcpp::NumericVector p0, bool store_kernel);
RcppExport SEXP _BKP_twin_dkp_posterior_rcpp(SEXP Xquery_normSEXP, SEXP Xtrain_normSEXP, SEXP YSEXP, SEXP g_indicesSEXP, SEXP local_indicesSEXP, SEXP theta_gSEXP, SEXP theta_lSEXP, SEXP global_kernelSEXP, SEXP local_kernelSEXP, SEXP isotropicSEXP, SEXP priorSEXP, SEXP r0SEXP, SEXP p0SEXP, SEXP store_kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xquery_norm(Xquery_normSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xtrain_norm(Xtrain_normSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type g_indices(g_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type local_indices(local_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta_g(theta_gSEXP);
    Rcpp::traits::input_parameter< double >::type theta_l(theta_lSEXP);
    Rcpp::traits::input_parameter< std::string >::type global_kernel(global_kernelSEXP);
    Rcpp::traits::input_parameter< std::string >::type local_kernel(local_kernelSEXP);
    Rcpp::traits::input_parameter< bool >::type isotropic(isotropicSEXP);
    Rcpp::traits::input_parameter< std::string >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< double >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< bool >::type store_kernel(store_kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(twin_dkp_posterior_rcpp(Xquery_norm, Xtrain_norm, Y, g_indices, local_indices, theta_g, theta_l, global_kernel, local_kernel, isotropic, prior, r0, p0, store_kernel));
    return rcpp_result_gen;
END_RCPP
}
// twin_select_global_rcpp
Rcpp::List twin_select_global_rcpp(Rcpp::NumericMatrix twin_data, Rcpp::NumericMatrix Xnorm, std::size_t r, std::size_t runs, Rcpp::IntegerVector u1, std::size_t leaf_size, std::size_t n_threads);
RcppExport SEXP _BKP_twin_select_global_rcpp(SEXP twin_dataSEXP, SEXP XnormSEXP, SEXP rSEXP, SEXP runsSEXP, SEXP u1SEXP, SEXP leaf_sizeSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type twin_data(twin_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xnorm(XnormSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type r(rSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type runs(runsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type u1(u1SEXP);
    Rcpp::traits::input_parameter< std::size_t >::type leaf_size(leaf_sizeSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(twin_select_global_rcpp(twin_data, Xnorm, r, runs, u1, leaf_size, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// twin_local_indices_rcpp
Rcpp::IntegerMatrix twin_local_indices_rcpp(Rcpp::NumericMatrix Xtrain_norm, Rcpp::NumericMatrix Xquery_norm, Rcpp::IntegerVector g_indices, std::size_t l, std::size_t leaf_size);
RcppExport SEXP _BKP_twin_local_indices_rcpp(SEXP Xtrain_normSEXP, SEXP Xquery_normSEXP, SEXP g_indicesSEXP, SEXP lSEXP, SEXP leaf_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xtrain_norm(Xtrain_normSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xquery_norm(Xquery_normSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type g_indices(g_indicesSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type l(lSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type leaf_size(leaf_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(twin_local_indices_rcpp(Xtrain_norm, Xquery_norm, g_indices, l, leaf_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BKP_get_prior_rcpp", (DL_FUNC) &_BKP_get_prior_rcpp, 8},
    {"_BKP_kernel_matrix_rcpp", (DL_FUNC) &_BKP_kernel_matrix_rcpp, 5},
    {"_BKP_loss_fun_rcpp", (DL_FUNC) &_BKP_loss_fun_rcpp, 10},
    {"_BKP_optimize_bkp_theta_rcpp", (DL_FUNC) &_BKP_optimize_bkp_theta_rcpp, 16},
    {"_BKP_optimize_dkp_theta_rcpp", (DL_FUNC) &_BKP_optimize_dkp_theta_rcpp, 15},
    {"_BKP_qbetabinom_rcpp", (DL_FUNC) &_BKP_qbetabinom_rcpp, 4},
    {"_BKP_shepard_m_rcpp", (DL_FUNC) &_BKP_shepard_m_rcpp, 4},
    {"_BKP_shepard_m_loo_rcpp", (DL_FUNC) &_BKP_shepard_m_loo_rcpp, 3},
    {"_BKP_twin_bkp_posterior_rcpp", (DL_FUNC) &_BKP_twin_bkp_posterior_rcpp, 15},
    {"_BKP_twin_dkp_posterior_rcpp", (DL_FUNC) &_BKP_twin_dkp_posterior_rcpp, 14},
    {"_BKP_twin_select_global_rcpp", (DL_FUNC) &_BKP_twin_select_global_rcpp, 7},
    {"_BKP_twin_local_indices_rcpp", (DL_FUNC) &_BKP_twin_local_indices_rcpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_BKP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
