# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_prior_rcpp <- function(model, prior, r0, p0 = NULL, y = NULL, m = NULL, Y = NULL, K = NULL) {
    .Call(`_BKP_get_prior_rcpp`, model, prior, r0, p0, y, m, Y, K)
}

kernel_matrix_rcpp <- function(X, Xprime = NULL, theta = as.numeric( c(0.1)), kernel = "gaussian", isotropic = TRUE) {
    .Call(`_BKP_kernel_matrix_rcpp`, X, Xprime, theta, kernel, isotropic)
}

loss_fun_rcpp <- function(model, loss, K, y = NULL, m = NULL, Y = NULL, alpha0 = NULL, beta0 = NULL, alpha0_mat = NULL, data_scale = NULL) {
    .Call(`_BKP_loss_fun_rcpp`, model, loss, K, y, m, Y, alpha0, beta0, alpha0_mat, data_scale)
}

optimize_bkp_theta_rcpp <- function(Xnorm, y, m, prior, r0, p0, loss, kernel, isotropic, init_gamma, lower, upper, max_iter, n_threads = 1L, ess = "none", m_shepard_loo = NULL) {
    .Call(`_BKP_optimize_bkp_theta_rcpp`, Xnorm, y, m, prior, r0, p0, loss, kernel, isotropic, init_gamma, lower, upper, max_iter, n_threads, ess, m_shepard_loo)
}

optimize_dkp_theta_rcpp <- function(Xnorm, Y, prior, r0, p0, loss, kernel, isotropic, init_gamma, lower, upper, max_iter, n_threads = 1L, ess = "none", m_shepard_loo = NULL) {
    .Call(`_BKP_optimize_dkp_theta_rcpp`, Xnorm, Y, prior, r0, p0, loss, kernel, isotropic, init_gamma, lower, upper, max_iter, n_threads, ess, m_shepard_loo)
}

qbetabinom_rcpp <- function(prob, size, alpha, beta) {
    .Call(`_BKP_qbetabinom_rcpp`, prob, size, alpha, beta)
}

shepard_m_rcpp <- function(Xquery_norm, Xtrain_norm, m, power = 2.0) {
    .Call(`_BKP_shepard_m_rcpp`, Xquery_norm, Xtrain_norm, m, power)
}

shepard_m_loo_rcpp <- function(Xnorm, m, power = 2.0) {
    .Call(`_BKP_shepard_m_loo_rcpp`, Xnorm, m, power)
}

twin_bkp_posterior_rcpp <- function(Xquery_norm, Xtrain_norm, y, m, g_indices, local_indices, theta_g, theta_l, global_kernel, local_kernel, isotropic, prior, r0, p0, store_kernel = FALSE) {
    .Call(`_BKP_twin_bkp_posterior_rcpp`, Xquery_norm, Xtrain_norm, y, m, g_indices, local_indices, theta_g, theta_l, global_kernel, local_kernel, isotropic, prior, r0, p0, store_kernel)
}

twin_dkp_posterior_rcpp <- function(Xquery_norm, Xtrain_norm, Y, g_indices, local_indices, theta_g, theta_l, global_kernel, local_kernel, isotropic, prior, r0, p0, store_kernel = FALSE) {
    .Call(`_BKP_twin_dkp_posterior_rcpp`, Xquery_norm, Xtrain_norm, Y, g_indices, local_indices, theta_g, theta_l, global_kernel, local_kernel, isotropic, prior, r0, p0, store_kernel)
}

twin_select_global_rcpp <- function(twin_data, Xnorm, r, runs, u1, leaf_size = 8L, n_threads = 1L) {
    .Call(`_BKP_twin_select_global_rcpp`, twin_data, Xnorm, r, runs, u1, leaf_size, n_threads)
}

twin_local_indices_rcpp <- function(Xtrain_norm, Xquery_norm, g_indices, l, leaf_size = 8L) {
    .Call(`_BKP_twin_local_indices_rcpp`, Xtrain_norm, Xquery_norm, g_indices, l, leaf_size)
}

